site_name: Dune Docs
site_url: https://dune-mkdocs-material.vercel.app/
repo_url: https://github.com/duneanalytics/docs
theme:
  name: material
  logo: assets/dune-icon-only.png
  favicon: assets/dune-icon-only.png
  palette:
    primary: indigo
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/DuneAnalytics
    - icon: fontawesome/brands/discord 
      link: https://discord.com/invite/ErrzwBz
    - icon: fontawesome/brands/github 
      link: https://github.com/duneanalytics
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - awesome-pages
  - mkdocs-video
extra:
  generator: false
extra_css:
  - stylesheets/extra.css